micronaut:
  application:
    name: relatorioService
  server:
    port: -1

mongodb:
  uri: 'mongodb://root:e296cd9f@ms-mongo:27017/admin'

consul:
  client:
    registration:
      enabled: true
    defaultZone: "ms-consul:8500"

kafka:
  bootstrap:
    servers: kafka-server:9092